name: Lint & PyTest on action
permissions:
  issues: read
  contents: write
  checks: write
  pull-requests: write

on:
  - push



jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]

    steps:
    - name: Job fail
      continue-on-error: true
      run: |
        exit 1
    - name: Next job
      run: |
        echo Hello
